### ISSUE TITLE
Doesnt seem to work

### ISSUE THREAD

**Issue by Moondee** [jeanlauliac/semantic-js-editor#1]
Hi 

$ ./build.js 
13:49:06  Starting to update project
13:49:06  Listening on port 8080
13:49:06  **\* Failed to write file output/index.html
Error: ENOENT, open 'output/index.html'
13:49:06  **\* Failed to write file output/bundle.js
Error: ENOENT, open 'output/bundle.js'
13:49:06  **\* Failed to write file output/bundle.css
Error: ENOENT, open 'output/bundle.css'
13:49:06  lib/JSEditor.js:40:9  warn   flattenPath is defined but never used  no-unused-vars
13:49:06  lib/tokenize.js:3:7  warn   Token is defined but never used  no-unused-vars
13:49:07  lib/tokenizers/tokenizeBinaryOp.js:61:42  warn   index is defined but never used  no-unused-vars
13:49:07  lib/tokenizers/tokenizeLiteral.js:6:55  warn   tokenize is defined but never used  no-unused-vars
13:49:07  lib/tokenizers/tokenizeUnaryOp.js:10:6  warn   rightContext is defined but never used  no-unused-vars
13:49:07  lib/tokenizers/tokenizeUnit.js:15:42  warn   index is defined but never used  no-unused-vars

and http://localhost:8080 doesnt show anything.

Running on Mac

**Comment by jeanlauliac** [comment]
You're right, forgot to mkdir the output directory — now fixed, thanks :)
